version: '3.9'


services:
  db:
    container_name: neo4j
    image: neo4j:5.26
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD", "wget", "http://localhost:7474"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "127.0.0.1:5001:5001"
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    volumes:
      - ./backend/db:/app/db:ro
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: frontend
    build:
      context: ./frontent
    ports:
      - "127.0.0.1:80:80"

volumes:
  neo4j_data:
