version: '3.9'

services:
  neo4j:
    image: neo4j:5.26
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/12345678"
    volumes:
      - neo4j_data:/data

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=12345678
    depends_on:
      - neo4j

  frontend:
    build:
      context: ./frontent
    ports:
      - "80:80"

volumes:
  neo4j_data:
