version: '3.9'

services:
  neo4j:
    image: neo4j:5.26
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/12345678"  # Замените на ваш пароль
    volumes:
      - neo4j_data:/data

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - neo4j

  frontend:
    build:
      context: ./frontent
    ports:
      - "4200:4200"

volumes:
  neo4j_data:
